/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedCalendarRouteImport } from './routes/_protected/calendar'
import { Route as ProtectedAiRouteImport } from './routes/_protected/ai'
import { Route as ProtectedAgentsRouteImport } from './routes/_protected/agents'
import { Route as ProtectedAgentsAgentIdChatRouteImport } from './routes/_protected/agents/$agentId.chat'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCalendarRoute = ProtectedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAiRoute = ProtectedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentsRoute = ProtectedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentsAgentIdChatRoute =
  ProtectedAgentsAgentIdChatRouteImport.update({
    id: '/$agentId/chat',
    path: '/$agentId/chat',
    getParentRoute: () => ProtectedAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/agents': typeof ProtectedAgentsRouteWithChildren
  '/ai': typeof ProtectedAiRoute
  '/calendar': typeof ProtectedCalendarRoute
  '/settings': typeof ProtectedSettingsRoute
  '/agents/$agentId/chat': typeof ProtectedAgentsAgentIdChatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/agents': typeof ProtectedAgentsRouteWithChildren
  '/ai': typeof ProtectedAiRoute
  '/calendar': typeof ProtectedCalendarRoute
  '/settings': typeof ProtectedSettingsRoute
  '/': typeof ProtectedIndexRoute
  '/agents/$agentId/chat': typeof ProtectedAgentsAgentIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/_protected/agents': typeof ProtectedAgentsRouteWithChildren
  '/_protected/ai': typeof ProtectedAiRoute
  '/_protected/calendar': typeof ProtectedCalendarRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/agents/$agentId/chat': typeof ProtectedAgentsAgentIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/test'
    | '/agents'
    | '/ai'
    | '/calendar'
    | '/settings'
    | '/agents/$agentId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/test'
    | '/agents'
    | '/ai'
    | '/calendar'
    | '/settings'
    | '/'
    | '/agents/$agentId/chat'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/test'
    | '/_protected/agents'
    | '/_protected/ai'
    | '/_protected/calendar'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/agents/$agentId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/calendar': {
      id: '/_protected/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ProtectedCalendarRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ai': {
      id: '/_protected/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof ProtectedAiRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agents': {
      id: '/_protected/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ProtectedAgentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agents/$agentId/chat': {
      id: '/_protected/agents/$agentId/chat'
      path: '/$agentId/chat'
      fullPath: '/agents/$agentId/chat'
      preLoaderRoute: typeof ProtectedAgentsAgentIdChatRouteImport
      parentRoute: typeof ProtectedAgentsRoute
    }
  }
}

interface ProtectedAgentsRouteChildren {
  ProtectedAgentsAgentIdChatRoute: typeof ProtectedAgentsAgentIdChatRoute
}

const ProtectedAgentsRouteChildren: ProtectedAgentsRouteChildren = {
  ProtectedAgentsAgentIdChatRoute: ProtectedAgentsAgentIdChatRoute,
}

const ProtectedAgentsRouteWithChildren = ProtectedAgentsRoute._addFileChildren(
  ProtectedAgentsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAgentsRoute: typeof ProtectedAgentsRouteWithChildren
  ProtectedAiRoute: typeof ProtectedAiRoute
  ProtectedCalendarRoute: typeof ProtectedCalendarRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAgentsRoute: ProtectedAgentsRouteWithChildren,
  ProtectedAiRoute: ProtectedAiRoute,
  ProtectedCalendarRoute: ProtectedCalendarRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
